name: school_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_modular: ^5.0.3
  intl: ^0.18.1
  json_annotation: ^4.7.0
  mask_text_input_formatter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  json_serializable: ^6.4.0
  mocktail: ^1.0.0



flutter:
  uses-material-design: true

  assets:
  - assets/images/
